# Generated by Django 3.0 on 2023-03-09 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipe',
        ),
    ]
